Rwanda CHOGM 2022
mbonabucya/Microverse-capstone-1 pull request #1
Opened 2022-06-23 15:38 UTC by mbonabucya

## Rwanda CHOGM 2022

add linters configuration
Add index.html ,  index.js , style.css
add about.html ,about.css , about.js
add Pop up menu (hamburger button ) to all pages
[Liveo Demo Video](https://www.loom.com/share/e1d5d0c1844a402eb3c4fb5deed9ae78)

2022-06-23 17:12 UTC, KDlamini requested changes
### Hi @mbonabucya 🙋‍♀️,  

Excellent work! 💯 
You have done a great job creating a conference page using the design specifications.🥳 
There are some issues that you still need to work on to improve your project according to the requirements. You are almost there! 💪🏾 

## Highlights 🌞 
✔️  The [JavaScript](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md) & [HTML & CSS](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/html_css_best_practices.md) linters are set up correctly
✔️  Appropriate credit to [Cindy Shin](https://www.behance.net/adagio07)appropriate credit to [Cindy Shin](https://www.behance.net/adagio07) the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)the [author of the original design](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)
✔️  The pages use the same colors, for text, backgrounds, borders, etc, from the original design.
✔️  Correct PR description
✔️  Commit messages are meaningful
✔️  No linter errors

## Required Changes ♻️
 
**Kindly look through the comments below 👇 for required changes**

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers 🥂  and Happy coding!!! 👯 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @KDlamini  in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-23 17:12 UTC, KDlamini commented on README.md
> +
Kindly record a video presenting the features of the project with a maximum length of 5 minutes which must contain a clear and objective description about the project.

- You can either attach the link on the README or PR description.

2022-06-23 17:12 UTC, KDlamini commented on README.md
> +
Kindly add a working link to the `issues` page in the README.

2022-06-23 17:12 UTC, KDlamini commented on index.html
> +      </nav>
The desktop size navbar must be divided into a top dark bar and a bottom white bar. The top short bar section with social media links, logout, and language links aligned to the right as per [Behance design ](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015)specifications.

Your design:
![image](https://user-images.githubusercontent.com/38088818/175348590-cc6dd7fc-bb6e-4d63-b383-42ea5f630e32.png)

Behance design:
![image](https://user-images.githubusercontent.com/38088818/175349351-31e8d06e-c693-4dfd-b3ce-47d1ddf602af.png)

2022-06-23 17:12 UTC, KDlamini commented on about.html
> +            </div>
The desktop size About Page footer should have have a dark background.

Your about footer:
![image](https://user-images.githubusercontent.com/38088818/175351490-0a0dba35-e7f2-4ba4-b4d8-e1af2719fb7b.png)

Behance design About footer:
![image](https://user-images.githubusercontent.com/38088818/175351622-ad610a2c-db66-4a67-8b58-2e1405fc148d.png)

2022-06-23 17:12 UTC, KDlamini commented on about.html
> +      </h4>
Kindly make sure that the past meetings cards have a visible background image with a background color overlay, year, and event description.

Your past event cards:
![image](https://user-images.githubusercontent.com/38088818/175352744-35069fa4-22a1-4167-89bd-ffa064f7e111.png)

Behance past events:
![image](https://user-images.githubusercontent.com/38088818/175353138-33032486-8ec9-4d4b-a487-3c05e5f744b6.png)

2022-06-25 10:50 UTC, topeogunleye approved these changes
### Hi @mbonabucya, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title :heavy_check_mark:
 
> ## [Optional] suggestions:
> * Nothing to mention.
> 
> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-25 11:05 UTC, merged